apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/jaeger:2.0.0
          args:
            - --set
            - receivers.otlp.protocols.grpc.endpoint=0.0.0.0:4317
            - --set
            - receivers.otlp.protocols.http.endpoint=0.0.0.0:4318
          ports:
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
