replicaCount: 1

image:
  repository: mercadona/product-service
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent
  pullSecrets: []

containerPort: 8082

service:
  type: ClusterIP
  port: 8080
  targetPort: 8082
  nodePort: null

probes:
  readiness:
    path: /actuator/health
    initialDelaySeconds: 15
    periodSeconds: 10
  liveness:
    path: /actuator/health
    initialDelaySeconds: 30
    periodSeconds: 15

env: []
