spring.application.name=api-gateway
server.port=8080
management.endpoints.web.exposure.include=health,info,prometheus
downstream.user-service-url=${USER_SERVICE_URL:http://localhost:8081}
downstream.order-service-url=${ORDER_SERVICE_URL:http://localhost:8083}
downstream.product-service-url=${PRODUCT_SERVICE_URL:http://localhost:8082}

otel.resource.attributes.service.name=api-gateway
otel.resource.attributes.service.namespace=ecommerce-platform
otel.resource.attributes.deployment.environment=minikube

otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none

otel.exporter.otlp.endpoint=http://otel-collector.observability.svc.cluster.local:4318
otel.exporter.otlp.protocol=http/protobuf
