replicaCount: 1

image:
  repository: mercadona/api-gateway
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent
  pullSecrets: []

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  nodePort: null

probes:
  startup:
    enabled: true
    path: /actuator/health
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 24
  readiness:
    path: /actuator/health
    initialDelaySeconds: 20
    periodSeconds: 10
  liveness:
    path: /actuator/health
    initialDelaySeconds: 90
    periodSeconds: 15

env: []

