spring.application.name=product-service
server.port=8082
management.endpoints.web.exposure.include=health,info,prometheus
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce_platform}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ecommerce}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ecommerce123}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=product_service
spring.flyway.create-schemas=true
spring.flyway.schemas=product_service
spring.flyway.default-schema=product_service

otel.resource.attributes.service.name=product-service
otel.resource.attributes.service.namespace=ecommerce-platform
otel.resource.attributes.deployment.environment=minikube

otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none

otel.exporter.otlp.endpoint=http://otel-collector.observability.svc.cluster.local:4318
otel.exporter.otlp.protocol=http/protobuf
